Book trip add -> main
StartFuture/novi-backend pull request #25
Opened 2023-05-29 21:57 UTC by giovana-git

2023-05-29 23:08 UTC, kilerhg requested changes

2023-05-29 23:08 UTC, kilerhg commented on app/routes/travel copy.py
Arquivo copy é utilizado?

2023-06-02 21:28 UTC, GabrielCecconi25 commented on app/routes/travel copy.py
Não, vou ajustar os erros aqui
:P

2023-06-02 21:59 UTC, kilerhg approved these changes
LGTM!

2023-06-02 22:13 UTC, merged